os: linux
dist: trusty
language: php

php:
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- nightly

matrix:
  allow_failures:
  - php: 7.3
  - php: nightly

branches:
  only:
  - master
  - /^\d+\.x$/
  - /^\d+\.\d+\.\d+$/

install:
- composer install --prefer-dist

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit

after_success:
  - if [[ "7.1" == "${TRAVIS_PHP_VERSION}" ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi
  - php vendor/bin/phpbench run --report=default

cache:
  directories:
  - $HOME/.composer/cache/files
  - vendor
