name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: MilesChou/composer-action/7.3/install@master
      - uses: docker://php:7.3-alpine
        with:
          args: php vendor/bin/phpcs
      - uses: docker://php:7.3-alpine
        with:
          args: php vendor/bin/phpunit
